
default:
  envOverrides:
    - name: OTEL_COLLECTOR_NAME
      value: my-otel-collector.opentelemetry-ns

opentelemetry-operator:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

