default:
  envOverrides:
    # FIXME how to evolve this test?
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: app.eng.team=$(TEAM_NAME)

components:
  accounting:
    envOverrides:
      - name: TEAM_NAME
        value: orion

  ad:
    envOverrides:
      - name: TEAM_NAME
        value: helix

  cart:
    envOverrides:
      - name: TEAM_NAME
        value: ring

  checkout:
    envOverrides:
      - name: TEAM_NAME
        value: orion

  currency:
    envOverrides:
      - name: TEAM_NAME
        value: orion

  email:
    envOverrides:
      - name: TEAM_NAME
        value: orion

  fraud-detection:
    envOverrides:
      - name: TEAM_NAME
        value: orion

  frontend:
    envOverrides:
      - name: TEAM_NAME
        value: ring

  load-generator:
    envOverrides:
      - name: TEAM_NAME
        value: ring

  payment:
    envOverrides:
      - name: TEAM_NAME
        value: orion

  product-catalog:
    envOverrides:
      - name: TEAM_NAME
        value: helix

  quote:
    envOverrides:
      - name: TEAM_NAME
        value: orion

  recommendation:
    envOverrides:
      - name: TEAM_NAME
        value: helix

  shipping:
    envOverrides:
      - name: TEAM_NAME
        value: orion

#opentelemetry-collector:
#  config:
#    processors:
#      attributes:
#        include:
#          match_type: strict
#          services:
#            - frontend-proxy
#        actions:
#          - key: "app.eng.team"
#            value: "ring"
#            action: insert
#    service:
#      pipelines:
#        traces:
#          processors:
#            - memory_limiter
#            - attributes
#            - spanmetrics
#            - batch

