#!/usr/bin/env bash
set -euo pipefail

set -x

ENV_FILE="$(dirname "$0")/.env"
# Validate required files exist
if [[ ! -f "$ENV_FILE" ]]; then
    echo "Error: .env file not found in current directory. "
    exit 1
fi

source "$ENV_FILE"

# WARNING: dont change "otel-demo" as it is used in the 'instrumentation' CRD defined in values.yaml


kubectl create secret generic grafana-cloud-auth \
  --namespace otel-demo  \
  --from-literal=GRAFANA_CLOUD_INSTANCE_ID="$GRAFANA_CLOUD_INSTANCE_ID" \
  --from-literal=GRAFANA_CLOUD_OTLP_ENDPOINT="$GRAFANA_CLOUD_OTLP_ENDPOINT" \
  --from-literal=GRAFANA_CLOUD_API_KEY="$GRAFANA_CLOUD_API_KEY" \
  --from-literal=GRAFANA_CLOUD_BASIC_AUTH_HEADER="$GRAFANA_CLOUD_BASIC_AUTH_HEADER" \
  || echo "WARNING Secret 'grafana-cloud-auth' already exists in namespace 'otel-demo', continuing..."
